require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rake
  - rubocop-performance

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  DisplayStyleGuide: true
  ExtraDetails: true

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Style/WordArray:
  EnforcedStyle: brackets

Style/AndOr:
  Enabled: true

