inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  DisplayStyleGuide: true

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rake
  - rubocop-performance

