name: Continuous Integration
on: 
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    env:
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Setup test database
        run: bundle exec rails db:prepare
      - name: Setup test assets
        run: bundle exec rails assets:precompile
      - name: Run all tests, linting, and checks
        run: bin/test
